const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "919330954192"
const SESSION_ID = "PRABATH-MD~dCMGSLhK#NDpwwepTVxeKHqJz_WWMFTQA82nYIk-b6xxEHCQK_so"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
